Add failing test for autocomplete with dynamic type
This will cause axe to throw an error like:

> TypeError: Cannot read property 'replace' of null

I believe that the problem might be related to getLiteralPropValue
returning `null` instead of `undefined` for dynamic props.